name = "aegis"
description = "ÆGIS PQC Kernel & SPARK Verification"
version = "0.1.0"
authors = ["ÆGIS Operator <operator@aegis.local>"]
maintainers = ["ÆGIS Operator <operator@aegis.local>"]
licenses = "MIT"

[[depends-on]]
gnatprove = "*"
