name: ÆGIS SPARK Verification

on: [push, pull_request]

jobs:
  prove:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alire (Ada Package Manager)
        uses: alire-project/setup-alire@v3

      - name: Configure Toolchain and Verify with GNATprove
        run: |
          # Tvinga Alire att ladda både kompileraren och gnatprove i sessionen
          alr --non-interactive toolchain --select gnat_native=14.2.1 gnatprove
          
          # Kör formell verifiering
          gnatprove -P aegis.gpr --mode=all --spark-debug
